name: Pack release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Archive MS SQL
        run: |
          tar cvzf mssqlserver.tar.gz "mssqlserver/"
          zip -r mssqlserver.zip "mssqlserver/"
          
      - name: Archive PostgreSQL
        run: |
          tar cvzf postgresql.tar.gz "postgresql/"
          zip -r postgresql.zip "postgresql/"

      - name: Archive Docs
        run: |
          mkdir tmp && cd tmp
          cp -r ../docs docs
          mv docs/app_apache docs/app && rm -r docs/app_nginx
          tar cvzf ../docs_apache.tar.gz "docs/"
          zip -r ../docs_apache.zip "docs/"
          rm -r docs
          cp -r ../docs docs
          mv docs/app_nginx docs/app && rm -r docs/app_apache
          tar cvzf ../docs_nginx.tar.gz "docs/"
          zip -r ../docs_nginx.zip "docs/"
          rm -r docs
          cd .. && rm -r tmp
          
      - name: Archive Storage
        run: |
          mkdir tmp && cd tmp
          cp -r ../storage/app_apache storage
          tar cvzf ../storage_apache.tar.gz "storage/"
          zip -r ../storage_apache.zip "storage/"
          rm -r storage
          cp -r ../storage/app_nginx storage
          tar cvzf ../storage_nginx.tar.gz "storage/"
          zip -r ../storage_nginx.zip "storage/"
          rm -r storage
          cd .. && rm -r tmp
          
      - uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allow_override: true
          tag: '5.0'
          name: '5.0'
          body: >
            WSS Docs 5 Docker Compose Configuration
          gzip: folders
          files: >
            mssqlserver.zip
            mssqlserver.tar.gz
            postgresql.zip
            postgresql.tar.gz
            docs_apache.zip
            docs_apache.tar.gz
            docs_nginx.zip
            docs_nginx.tar.gz
            storage_apache.zip
            storage_apache.tar.gz
            storage_nginx.zip
            storage_nginx.tar.gz
            README.md
            
